apiVersion: v1
items:
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-connect-0
  spec:
    clustersScopeByIds:
      connectClusterId: kb.mosheconnect
      kafkaClusterId: s4s0aRJpTbeVGHKh0JA-Dg
    principal:
      name: connectAdmin
      type: user
    role: SecurityAdmin
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-connect-1
  spec:
    principal:
      name: connectAdmin
      type: user
    resourcePatterns:
    - name:  kb.connect-cluster-id
      patternType: LITERAL
      resourceType: Group
    - name:  kb.connect-cluster-id
      patternType: PREFIXED
      resourceType: Topic
    role: ResourceOwner
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-connect-2
  spec:
    principal:
      name: connectAdmin
      type: user
    resourcePatterns:
    - name: _confluent-monitoring
      patternType: PREFIXED
      resourceType: Topic
    role: DeveloperWrite

- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-schemaregistry-0
  spec:
    clustersScopeByIds:
      schemaRegistryClusterId: id_schemaregistry_kb
      kafkaClusterId: s4s0aRJpTbeVGHKh0JA-Dg
    principal:
      name: schemaregistryUser
      type: user
    role: SecurityAdmin
- apiVersion: platform.confluent.io/v1beta1
  kind: ConfluentRolebinding
  metadata:
    name: internal-schemaregistry-1
  spec:
    principal:
      name: schemaregistryUser
      type: user
    resourcePatterns:
    - name: _confluent-license
      patternType: LITERAL
      resourceType: Topic
    - name: _schemas_schemaregistryUser_kb
      patternType: LITERAL
      resourceType: Topic
    - name: id_schemaregistry_kb 
      patternType: LITERAL
      resourceType: Group
    role: ResourceOwner
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
